// Generated by CoffeeScript 1.10.0
var coffee, gulp, http, livereload, pug, st;

st = require('st');

http = require('http');

gulp = require('gulp');

coffee = require('gulp-coffee');

pug = require('gulp-pug');

livereload = require('gulp-livereload');

gulp.task('build:coffee', function() {
  return gulp.src('src/**/*.coffee').pipe(coffee()).pipe(gulp.dest('dist')).pipe(livereload());
});

gulp.task('build:pug', function() {
  return gulp.src('src/**/*.jade').pipe(pug()).pipe(gulp.dest('dist')).pipe(livereload());
});

gulp.task('copy:js', function() {
  return gulp.src('src/**/*.js').pipe(gulp.dest('dist'));
});

gulp.task('copy:libs', function() {
  return gulp.src(['libs/jquery-ui/themes/base/jquery-ui.css', 'libs/bootstrap/dist/css/bootstrap.css', 'libs/jqGrid/css/ui.jqgrid.css', 'libs/jqGrid/css/ui.jqgrid-bootstrap.css', 'libs/jqGrid/css/ui.jqgrid-bootstrap-ui.css', 'libs/jquery/dist/jquery.js', 'libs/jqGrid/js/jquery.jqGrid.js', 'libs/bootstrap/dist/js/bootstrap.js', 'libs/highcharts/highcharts.js']).pipe(gulp.dest('dist/libs'));
});

gulp.task('copy:images', function() {
  return gulp.src('libs/jquery-ui/themes/base/images/**/*.*').pipe(gulp.dest('dist/libs/images'));
});

gulp.task('copy:fonts', function() {
  return gulp.src('libs/bootstrap/dist/fonts/**/*.*').pipe(gulp.dest('dist/fonts'));
});

gulp.task('copy', ['copy:js', 'copy:libs', 'copy:images', 'copy:fonts']);

gulp.task('build', ['build:coffee', 'build:pug', 'copy']);

gulp.task('server', ['build'], function(done) {
  var port;
  port = 8081;
  console.log("Server ready for requests: http://localhost:" + port + "/");
  return http.createServer(st({
    path: __dirname + '/dist',
    index: 'index.html',
    cache: false
  })).listen(port, done);
});

gulp.task('watch', ['server'], function() {
  livereload.listen({
    basePath: 'dist'
  });
  gulp.watch('src/**/*.jade', ['build:pug']);
  return gulp.watch('src/**/*.coffee', ['build:coffee']);
});
